dialog = [
    "PP: Destin?\\ Are you there?\\ It's me,\\ Brannon\\.\\.\\.\\ Davidson.",
    "DX: \\\\Brannon",
    "DX: holy crap",
    "PP: It's been a long time,\\ hasn't it?",
    "DX: it sure has",
    "DX: how have you been?",
    "PP: Things have been crazy.\\ I've gone through so much over the past five years",
    "DX: you have no idea dude",
    "PP: I've gone back to Arkansas for a bit so I could say hi to my family",
    "PP: I've been living in Oregon for a while and I got homesick",
    "PP: Since I'm here,\\ I was wondering if you could help me contact the rest of the friend group.\\.\\.\\ if it still exists",
    "DX: sure",
    "DX: they may be a bit different from what you remember but its fine",
    "DX: also\\ you moved to oregon?",
    "PP: yeah",
    "DX: bro",
    "PP: anyway,\\ I wanna talk to everyone",
    "DX: yeah ill get them",
    "\n——— Diaxr started messaging Gertieboi ———",
    "DX: garrett",
    "GB: Dude what i just woke up",
    "DX: brannons back join our chat now",
    "GB: What",
    "DX: come here",
    "GB: Wait WHAT",
    "\n——— Gertieboi joined the chat ———",
    "PP: Hey Garrett",
    "GB: BRANNON",
    "GB: Been a while",
    "PP: i know",
    "DX: let me get landon",
    "\n——— Diaxr started messaging Land0Rex ———",
    "DX: brannon just came back",
    "DX: landon",
    "DX: LANDON",
    "LR: What",
    "DX: BRANNON IS BACK YOU MORON",
    "LR: Oh",
    "LR: Oh wait what the",
    "\n——— Land0Rex joined the chat ———",
    "PP: sup,\\ Landon?",
    "LR: yooo brannon",
    "GB: Idiot",
    "PP: well everyone,\\ it's great to see you all again",
    "LR: same",
    "DX: what made you think you can just come back",
    "PP: uhhh...\\ what?\\ If I'm not welcome then...",
    "DX: im joking",
    "DX: but you were gone for five years brannon",
    "PP: yes,\\ I know",
    "PP: I want to make up for that.\\ I'm offering you guys to go hiking with me",
    "GB: Hiking??",
    "LR: Uhhh idk bout that",
    "DX: what",
    "PP: it's in Vancouver,\\ Canada",
    "PP: listen.\\ I wanna climb a mountain with you guys",
    "DX: what are you talking about",
    "GB: Im not doing that",
    "LR: What mountain is it",
    "PP: have you heard all those crazy rumors about this one magical mountain called Mount Celeste?",
    "LR: What",
    "DX: theres no way you believe that",
    "LR: There is no way",
    "PP: i've heard that there's some really cool sights on it,\\ and if there ARE any crazy things that happen it'd be awesome to see them together",
    "LR: I mean I'm down for cool sights but a MOUNTAIN?",
    "GB: Uhh",
    "DX: have you even gone hiking before",
    "PP: one time in Cub Scouts,\\ yeah",
    "DX: brannon that was like 10 years ago",
    "PP: a little less,\\ but...",
    "DX: i mean hiking sounds like good exercise but",
    "GB: Yeah yeah i know",
    "DX: no you dont",
    "GB: You wanna go",
    "PP: guys...",
    "LR: I'm not sure brannon",
    "LR: I mean it sounds fun but I don't really think that's my sort of thing",
    "PP: welp,\\ sorry for asking I guess",
    "GB: Homestuck?",
    "PP: no",
    "DX: garrett",
    "LR: Yeah,\\ I don't really wanna go.\\ Maybe one day...",
    "GB: Me neither",
    "DX: vancouver is really far away",
    "DX: im not sure if i wanna pay for the travel",
    "PP: i'll pay for everything!\\ I forgot to say!",
    "GB: Oh wait what",
    "DX: have you been saving up for this",
    "PP: yup",
    "DX: ok if its so important to you i guess ill go",
    "GB: If i dont have to pay for anything then sure why not",
    "LR: If you're all going then I'll go too",
    "PP: how is your insulin going to work tho Destin",
    "DX: ill just take the thing with me",
    "LR: What thing",
    "DX: i have diabetes remember",
    "LR: Oh yeah",
    "GB: Your type 2 right",
    "DX: garrett im going to kill you",
    "LR: Lol",
    "PP: wait where does everyone else live?",
    "DX: we can just send you our locations",
    "> Diaxr sent his location.",
    "PP: fayetteville?",
    "DX: yeah",
    "DX: where are you",
    "PP: i'm actually in fayetteville too",
    "DX: conserve your gas",
    "DX: landon and garrett can drive here",
    "LR: Bro",
    "PP: thanks",
    "GB: Should we take anything",
    "PP: i brought you all your very own backpacks with all the mountain climbing gear you'll need.\\ Bring something to protect you from the cold and essentials like toothbrushes and stuff.\\ Snacks are good too",
    "DX: okay",
    "DX: also dont you need a permit for mountain climbing",
    "PP: yes,\\ but not for Celeste Mountain.\\ The government doesn't care.\\ I've looked into everything",
    "PP: BUT",
    "PP: You're all gonna need PASSPORTS to cross the Canadian border!",
    "GB: I think we got those",
    "DX: you are actually so lucky brannon",
    "DX: we went through that process almost two years ago just in case we went on vacation together for summer",
    "LR: But we never did",
    "PP: Dang",
    "DX: yeah landon is still upset that we didnt",
    "LR: It took me so long to get that stupid passport bro",
    "DX: also you guys can show up at,\\ like,\\ the city park",
    "DX: when do we need to be there",
    "PP: i'd appreciate it if you all showed up tomorrow around 3:30 p.m.",
    "GB: Ok",
    "DX: guess ill get my stuff",
    "DX: see you guys tomorrow",
    "LR: Bye",
    "PP: farewell,\\ everyone",
    "\n——— Chat ended ———",]

dialog2 = [
    "KD: Hey...",
    "PR: What",
    "KD: I'm going to be moving to Columbia",
    "PR: Gg",
    "KD: No,\\ like,\\ actually",
    "KD: I'm moving some time around mid-June",
    "PR: I can't believe that",
    "KD: Yeah ik it sucks",
    "KD: X3",
    "PR: Why are you moving",
    "KD: We have family over there and my parents can't afford living here,\\ so we had to fall back",
    "PR: uuuuuuguhghg whyyyy",
    "KD: I know",
    "KD: We can still chat tho!",
    "PR: I guess",
    "\nThe honk of a horn jars Patrick out of his texting.\\ It seems the man behind him is gracefully letting him know that there's a couple of inches to move forward.\n",
    "PR: Ok look I'm driving right now",
    "PR: I'll talk to you later",
    "KD: Cya"
]